version: '3.8'

services:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=info@themarto.es"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/acme.json:/letsencrypt/acme.json

  angular-app:
    build:
      context: ./angular-app
    container_name: angular-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.angular.rule=Host(`themarto.es`)"
      - "traefik.http.routers.angular.entrypoints=websecure"
      - "traefik.http.routers.angular.tls.certresolver=letsencrypt"
